pipeline {
    agent any
    // tools {
    //     maven 'Maven_3.9.2' // Replace with the specific Maven tool name and version
    // }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -Denforcer.skip=true clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Denforcer.skip=true test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
